language: go 

go:
- "1.14"

os:
  - linux

before_script:
  - curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https --yes
  - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  - sudo apt-get update
  - sudo apt-get install helm

script:
  - pushd cloud/kubernetes/helm
  - helm dep update
  - helm lint
  - pushd ../tests/template
  - export GO111MODULE=on
  - go test ./... 
  - popd
  
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - rpolishe@tibco.com
      - lmekala@tibco.com
      - nthota@tibco.com
      - ykalidin@tibco.com  