# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Cloud Providers: minikube, PKS, Azure, AWS-EKS, Openshift

#Required parameter to be passed for all cloud providers
cloudProvider: minikube

#Required parameter to be passed for cache, sharedNothing, sharedAll
omType: inmemory

#Required parameter to be passed for sharedNothing, sharedAll
persistentType: None

# Image name and pull policy required for be app
image: fdstoresn:v01
imagePullPolicy: IfNotPresent
imagePullSecrets:  #if required for azure

#Required for sharedAll in  all cloud providers
mysql:
  enabled: false #use true for sharedAll
  image: "mysql"
  imageTag: "5.7"
  args: [ "--lower_case_table_names=1","--sql_mode=IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" ]
  mysqlUser: root
  mysqlPassword: root
  mysqlRootPassword: password
  mysqlDatabase: BE_DATABASE #datbase name
  # persistence: 
  #   storageClass: "-" #Type of persistent volume claim

# Required for sharedNothing and sharedAll in AWS
aws-efs:
  enabled: false #use true for aws 
  replicaCount: 1
  efsProvisioner:
    efsFileSystemId: fs-e8f5fa68
    awsRegion: us-east-1

#*************************Agents Part****************************************************

#Required for cache, sharedNothing, sharedAll in  all cloud providers
cachenode:
  name: becacheagent
  replicaCount: 1
  containers:
    name: cachenode    
    env:
      PU1name: PU
      PU1value: cache
      PU2name: AS_DISCOVER_URL
      PU2value: "tcp://bediscovery-service:50000"

#Required for all applications in  all cloud providers
inferencenode:
  name: beinferenceagent
  replicaCount: 1
  containers:
    name: inferencenode
    env:
      PU1name: PU
      PU1value: default
      PU2name: AS_DISCOVER_URL
      PU2value: "tcp://bediscovery-service:50000"

#Required for cache, sharedNothing, sharedAll in  all cloud providers
discoverynode:
  name: bediscoverynode
  replicaCount: 1
  containers:
    name: discoverynode
    env:
      PU1name: PU
      PU1value: cache

#Required for sharedAll in all cloud providers
database:
  name: db-provider
  drivername: BACKINGSTORE_JDBC_DRIVER
  driverval: db_driver
  urlname: BACKINGSTORE_JDBC_URL
  urlval: db_url
  username: BACKINGSTORE_JDBC_USERNAME
  userval: db_username
  pwdname: BACKINGSTORE_JDBC_PASSWORD
  pwdval: db_pwd
  poolsizename: BACKINGSTORE_JDBC_POOL_SIZE
  poolsizeval: "db_pool_size"
  logintimeoutname: BACKINGSTORE_JDBC_LOGIN_TIMEOUT
  logintimeoutval: db_login_timeout

#*************************Service Part****************************************************
#Required for cache, sharedNothing, sharedAll in all cloud providers
discoveryservice:
  name: bediscovery-service
  ports:
    port: 50000
    protocol: TCP
  selector:
    name: bediscoverynode

#Required for all applications in all cloud providers
jmxservice:
  name: jmx-service
  selector:
    name: beinferenceagent
  ports:
    protocol: TCP
    port: 5555
    targetPort: 5555
  type: LoadBalancer

#Required for all applications in all cloud providers
beservice:
  name: beservice
  type: NodePort
  ports:
    name: port1
    protocol: TCP
    port: 8209

#Required for sharedAll in all cloud providers
mysqlservice:
  name: mysql
  clusterIP: None
  ports:
    port: 3306
    protocol: TCP
  selector:
    name: mysql


#*************************ConfigMap****************************************************

#Required for sharedAll in all cloud providers
configmap:
  name: db-provider
  dbdriver: com.mysql.jdbc.Driver
  dburl: jdbc:mysql://mysql-0.mysql.default.svc.cluster.local:3306/BE_DATABASE
  dbusername: BE_USER
  dbpwd: BE_USER
  dbpoolsize: 5
  dblogintimeout: 0

#*************************Volumes Part****************************************************

volumes:
  #Required for sharedNothing and sharedAll in all cloud providers
  snmountPath: "/mnt/tibco/be/data-store"
  snmountVolume: store
  accessModes: ["ReadWriteOnce"]
  storage: 0.5Gi
  storageClass: standard                    #Use default storage class in case of minikube and PKS persistent volumes
  snclaimVolume: pv0003                         #Update it for sharedNothing in Openshift
  saclaimVolume: pv0004                          #Update it for sharedAll in Openshift
  samountPath: "/var/lib/mysql"
  samountVolume: sastore
  #Required for sharedNothing and sharedAll in Azure
  azure:
    storageClassName: azurestorageclass
    skuName: Standard_LRS
    provisioner: kubernetes.io/azure-file
    dir_mode: 0777
    file_mode: 0777
    uid: 1000
    gid: 1000

persistentvolumes:
#Required for sharedNothing, sharedAll in Openshift.
  openshift:
    volume:
      snvolname: pv0003
      savolname: pv0004
      storage: 1Gi
      accessModes: ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      nfs:
        server: qa.lab.openshift.com       #update the servername
        snpath: /home/data/pv0003          #Update path for sharedNothing
        sapath: /home/data/pv0004          #Update path for sharedAll
