# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#Cloud Providers: minikube, PKS, Azure, AWS-EKS, Openshift

#Required parameter to be passed for all cloud providers
cloudProvider: minikube
#-----------------------------------------
cmType: AS2                     #cmType can be unclustered,AS2,FTL
omType: cache                   #omType can be inmemory,store,cache
bsType: sharedNothing1         #BackingStore can be None sharedNothing, store
storeType: None                 #storeType can be RDBMS, AS4, Cassandra
cacheType: AS2                  #cacheType can be AS2, ignite

# Image name and pull policy required for be app
image: ftlsnapp
imagePullPolicy: IfNotPresent
imagePullSecrets:  #if required for azure

#Required for store in  all cloud providers
mysql:
  enabled: false #use true for store
  image: "mysql"
  imageTag: "5.7"
  args: [ "--lower_case_table_names=1","--sql_mode=IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" ]
  mysqlUser: root
  mysqlPassword: root
  mysqlRootPassword: password
  mysqlDatabase: BE_DATABASE #datbase name
  # persistence: 
  #   storageClass: "-" #Type of persistent volume claim

# Required for sharedNothing and store in AWS
aws-efs:
  enabled: false #use true for aws 
  replicaCount: 1
  efsProvisioner:
    efsFileSystemId: fs-e8f5fa68
    awsRegion: us-east-1

#*************************FTL****************************************************

ftl:
  FTL_gv_REALM_SERVER: http://localhost:8585
  FTL_gv_REALM_NAME: cepFTLRealm
  FTL_gv_APP_NAME: cepFTLApp
  FTL_gv_CLUSTER_NAME: cepFTLCluster
  FTL_gv_PUBSUB_ENDPOINT: cepFTLDefaultEndpoint
  FTL_gv_MAP_ENDPOINT: cepFTLMapEndpoint
  FTL_gv_PERSISTENT_ENDPOINT: cepFTLPersistenceEndpoint
  FTL_gv_SHARED_ENDPOINT: cepFTLSharedEndpoint
  FTL_gv_USER_NAME: guest
  FTL_gv_USER_PWD: guest-pw

#*************************Agents Part****************************************************

#Required for cache, sharedNothing, store in  all cloud providers
cachenode:
  name: becacheagent
  replicaCount: 1
  containers:
    name: cachenode    
    env:
      PU1name: PU
      PU1value: cache
      PU2name: AS_DISCOVER_URL
      PU3name: IGNITE_DISCOVER_URL

#Required for all applications in  all cloud providers
inferencenode:
  name: beinferenceagent
  replicaCount: 1
  containers:
    name: inferencenode
    env:
      PU1name: PU
      PU1value: default
      PU2name: AS_DISCOVER_URL
      PU3name: IGNITE_DISCOVER_URL

#*************************Service Part****************************************************
#Required for cache, sharedNothing, store in all cloud providers
cacheservice:
  name: becache-service
  ports:
    port: 50000
    protocol: TCP
  selector:
    name: becacheagent

#Required for all applications in all cloud providers
jmxservice:
  name: jmx-service
  selector:
    name: beinferenceagent
  ports:
    protocol: TCP
    port: 5555
    targetPort: 5555
  type: LoadBalancer

#Required for all applications in all cloud providers
beservice:
  name: beservice
  type: NodePort              #LoadBalancer for azure, NodePort
  ports:
    name: port1
    protocol: TCP
    port: 8108

ignite:
  dis0: 47500
  dis1: 47501
  dis2: 47502
  dis3: 47503
  dis4: 47504
  dis5: 47505
  dis6: 47506
  dis7: 47507
  dis8: 47508
  dis9: 47509  

#*************************ConfigMap****************************************************

#Required for store in all cloud providers
configmap:
  name: db-provider
  dbdriver: com.mysql.jdbc.Driver
  dburl: jdbc:mysql://mysql-0.mysql.default.svc.cluster.local:3306/BE_DATABASE
  dbusername: BE_USER
  dbpwd: BE_USER
  dbpoolsize: 5
  dblogintimeout: 0

#Required for store in all cloud providers
database:
  name: db-provider
  drivername: BACKINGSTORE_JDBC_DRIVER
  driverval: db_driver
  urlname: BACKINGSTORE_JDBC_URL
  urlval: db_url
  username: BACKINGSTORE_JDBC_USERNAME
  userval: db_username
  pwdname: BACKINGSTORE_JDBC_PASSWORD
  pwdval: db_pwd
  poolsizename: BACKINGSTORE_JDBC_POOL_SIZE
  poolsizeval: "db_pool_size"
  logintimeoutname: BACKINGSTORE_JDBC_LOGIN_TIMEOUT
  logintimeoutval: db_login_timeout

nosqlconfigmap:
  name: nosql

cassconfigmap:
  name: cassandra
  cass_server_hostname: localhost
  cass_server_port: 9042
  cass_keyspace_name: testdb
  cass_username: cassandra
  cass_password: cassandra

cassdatabase:
  name: db-provider
  drivername: CASS_SERVER_HOSTNAME
  driverval: db_cass_server_hostname
  portname: CASS_SERVER_PORT
  portval: db_cass_server_port
  keyspacename: CASS_KEYSPACE_NAME
  keyspaceval: db_cass_keyspace_name
  username: CASS_USERNAME
  userval: db_cass_username
  pwdname: CASS_PASSWORD
  pwdval: db_cass_password

as4configmap:
  name: as4
  realm_url: http://192.168.0.110:8585
  sec_realm_url: http://192.168.0.110:8585
  grid_name: fd_store
  store_timeout: 5
  store_waittime: 0.1
  store_poolsize: 1

as4database:
  name: db-provider
  realmname: REALM_URL
  realmval: db_realm_url
  secrealmurlname: SEC_REALM_URL
  secrealmurlval: db_sec_realm_url
  gridname: GRID_NAME
  gridval: db_grid_name
  storetimeoutname: STORE_TIMEOUT
  storetimeoutval: db_store_timeout
  storewaittimename: STORE_WAITTIME
  storewaittimeval: "db_store_waittime"
  poolsizename: STORE_POOLSIZE
  poolsizeval: db_store_poolsize  

#*************************Volumes Part****************************************************
volumes:
  #Required for sharedNothing and store in all cloud providers
  snmountPath: "/mnt/tibco/be/data-store"
  snmountVolume: store
  accessModes: ["ReadWriteOnce"]
  storage: 0.5Gi
  storageClass: standard                    #Use default storage class in case of minikube and PKS persistent volumes
  snclaimVolume: pv0003                         #Update it for sharedNothing in Openshift
  saclaimVolume: pv0004                          #Update it for store in Openshift
  samountPath: "/var/lib/mysql"
  samountVolume: sastore
  #Required for sharedNothing and store in Azure
  azure:
    storageClassName: azurestorageclass
    skuName: Standard_LRS
    provisioner: kubernetes.io/azure-file
    dir_mode: 0777
    file_mode: 0777
    uid: 1000
    gid: 1000

persistentvolumes:
#Required for sharedNothing, store in Openshift.
  openshift:
    volume:
      snvolname: pv0003
      savolname: pv0004
      storage: 1Gi
      accessModes: ReadWriteOnce
      persistentVolumeReclaimPolicy: Recycle
      nfs:
        server: qa.lab.openshift.com       #update the servername
        snpath: /home/data/pv0003          #Update path for sharedNothing
        sapath: /home/data/pv0004          #Update path for store
