{{- range $i, $agent := .Values.agents }}
{{- if gt (int $agent.replicas) 0 }}
{{- $ssName := (printf "%s-%s" $.Release.Name $agent.name) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $ssName }}
spec:
  replicas: {{ $agent.replicas }}
  selector:
    matchLabels:
      name: {{ $ssName }}
  serviceName: {{ include "bechart.discoveryservice.name" $ }}
  template:
    metadata:
      labels:
        name: {{ $ssName }}
        {{- if $agent.cacheStorageEnabled }}
        cacheagent: "yes"
        {{- end }}
    spec:
{{ include "pullsecrets" $ | trim | indent 6 }}
{{ include "ignitesaname" $ | trim | indent 6 }}
{{- if $.Values.podAntiAffinity }}
{{ include "bechart.affinity" $ssName | trim | indent 6 }}
{{- end }}
      containers:
      - name: {{ $agent.name }}-container
        image: {{ $.Values.image }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        env:
        - name: PU
          value: {{ $agent.PU }}
        - name: ENGINE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{ include "gvproviders" $ | trim | indent 8 }}                
{{ include "discovery_url" $ | trim | indent 8 }}
{{ include "influx-grafana.data" $ | trim | indent 8 }}
{{ include "store.configMap" $ | trim | indent 8 }}
{{ include "bechart.resourceLimits" $ | trim | indent 8 }}
{{ include "healthcheck" $ | trim | indent 8 }}
{{ include "bechart.volumeMounts" $ | trim | indent 8 }}
{{- if $.Values.persistence.scSupportsReadWriteMany }}
{{ include "bechart.volumes" $ | trim | indent 6 }}
{{- else }}
{{ include "bechart.volumeClaimTemplates" $ | trim | indent 2 }}
{{- end }}
---
{{- end }}
{{- end }}