{{- range $i, $agent := .Values.agents }}
{{- if gt (int $agent.replicas) 0 }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-{{ $agent.name }}
spec:
  replicas: {{ $agent.replicas }}
  selector:
    matchLabels:
      name: {{ $.Release.Name }}-{{ $agent.name }}
  serviceName: {{ include "discoveryservice.fullname" $ }}
  template:
    metadata:
      labels:
        name: {{ $.Release.Name }}-{{ $agent.name }}
        {{- if $agent.cacheStorageEnabled }}
        cacheagent: "yes"
        {{- end }}
    spec:
{{ include "pullsecrets" $ | trim | indent 6 }}
{{ include "ignitesaname" $ | trim | indent 6 }}          
      containers:
      - name: {{ $agent.name }}-container
        image: {{ $.Values.image }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        env:
        - name: PU
          value: {{ $agent.PU }}
        - name: ENGINE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
{{ include "gvproviders" $ | trim | indent 8 }}                
{{ include "discovery_url" $ | trim | indent 8 }}
{{ include "influx-grafana.data" $ | trim | indent 8 }}
{{ include "store.configMap" $ | trim | indent 8 }}
{{ include "fargate-resource-memory" $ | trim | indent 8 }}
{{ include "healthcheck" $ | trim | indent 8 }}
{{ include "bechart.volumeMounts" $ | trim | indent 8 }}
{{ include "bechart.volumeClaimTemplates" $ | trim | indent 2 }}
---
{{- end }}
{{- end }}