{{- if or (eq .Values.cmType "AS2" ) (eq .Values.cmType "FTL" ) (eq .Values.cmType "unclustered" ) }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "jmxservice.fullname" . }}
spec:
  ports:
    - port: {{ .Values.jmxservice.ports.port }}
      protocol: TCP
  selector:
    name: {{ include "becacheagent.fullname" . }}
  type: {{ .Values.jmxservice.type }}
{{- end }}