{{- if or (eq .Values.cmType "AS2" ) (eq .Values.cmType "FTL" ) (eq .Values.cmType "unclustered" ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "beservice.fullname" . }}
spec:
  ports:
    - port: {{ .Values.beservice.ports.port }}
      protocol: TCP
  selector:
    name: {{ include "beinferenceagent.fullname" . }}
  type: {{ .Values.beservice.type }}
{{- end }}