{{- if or (eq .Values.cmType "AS2" ) (eq .Values.cmType "FTL" ) }}
{{- if and (eq .Values.cpType "azure" ) (eq .Values.omType "cache" ) }}
  {{- if or (eq .Values.bsType "sharedNothing" ) (eq .Values.bsType "store" ) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "azurestorageclass.fullname" . }}
provisioner: {{ .Values.volumes.azure.provisioner }}
mountOptions:
  - dir_mode={{ .Values.volumes.azure.dir_mode }}
  - file_mode={{ .Values.volumes.azure.file_mode }}
  - uid={{ .Values.volumes.azure.uid }}
  - gid={{ .Values.volumes.azure.gid }}
parameters:
  skuName: {{ .Values.volumes.azure.skuName }}
  {{- end }}
{{- end }}
{{- end }}
