name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: latest # default is latest
        
    - name: setup
      run: helm dep up
      working-directory: ./cloud/kubernetes/helm
      
    - name: test directory
      run: ls -R
      working-directory: cd ./../tests/template 


    - name: Test
      run:  go test -v ./... #cd /home/runner/work/be-tools/be-tools/cloud/kubernetes/helm & go test -v ./...
#       working-directory: ../tests/template
      
      
