name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: latest # default is latest
        
    - name: setup
      run: pushd cloud/kubernetes/helm & ls & helm dep up

    - name: Build
      run: pushd ../tests/template 

     
    - name: Test
      run:  pwd & go test -v ./... #cd /home/runner/work/be-tools/be-tools/cloud/kubernetes/helm & go test -v ./...
